apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-capstone
  labels:
    app: frontend-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-capstone
  template:
    metadata:
      labels:
        app: frontend-capstone
    spec:
      containers:
      - name: frontend-capstone
        image: frontend-capstone:latest
        ports:
        - containerPort: 8080