apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-capstone
  name: frontend-capstone-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/frontend-capstone-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-capstone
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}